### ISSUE TITLE
Displayed power is unstable when firing on RX200S

### ISSUE THREAD

**Issue by Daemones795** [arafey/openevic#20] opened 2017-04-19 00:45 UTC
using power mode at any wattage on the newest release, the wattage goes up and down insanely fast within the range of 6 watts above and below the set wattage. the vape is in mint condition, coils are 2 ohm and i only vape at 70 watts, i have done all of the basic hardware troubleshooting, (checking coils are good and are secure, my tank is secure, the tank and the mod are clean, and my 510 pin is perfect)

**Box Model:**
Reuleux rx200s with lg 2500mah he4 batts
**Coil setup:**
tfv8 with prebuilt v6 coil in it

**Comment by arafey** [comment] 2017-04-19 01:40
Did you have this problem on openevic only or does this problem also occur on myevic? 

Also, did you set it to HE4 under the menu option for battery model or is it set to Generic (GEN in the menu)?

**Comment by Daemones795** [comment] 2017-04-19 03:13
its set to he4 in the menu and im using the latest myevic how do i try openvic, i dont see a bin for it

**Comment by arafey** [comment] 2017-04-19 03:25
I can't help you with myevic-related problems. I only maintain my version, which is openevic (a fork of myevic).

You can get the newest version of openevic from the [releases page](https://github.com/arafey/openevic/releases).

**Comment by arafey** [comment] 2017-04-19 03:47
Something else that just came to mind about this in case it helps: Does it feel like it's swinging in terms of output power or is it just that the displayed value is swinging? Also, is it only the wattage or the amperage as well?

I'm closing this issue for now. If you have this problem with openevic as well, respond here and I'll consider reopening it. If you use openevic and don't have any issues, then respond here as well so I can change the tag.

**Comment by Daemones795** [comment] 2017-04-19 16:16
yeah i used the most recent version of the openevic generic and so far it has the same problem with less bouncing range, will check optimized version after work tonight

**Comment by arafey** [comment] 2017-04-19 16:50
Thanks for trying openevic. I look forward to hearing the results of running the optimized build. I would also recommend trying stock firmware to rule out an electrical or other hardware issue.

Please provide the following info (do all of these together, in order):
* battery volts when idle for at least 5 seconds after a cold start (should be at room temperature, not a few minutes after firing)
* battery volts/amps/watts when firing for at least 5 seconds (you may need multiple takes to get all this down)
* battery volts when idle for at least 5 seconds after firing (should be descending)

Some of these values will follow a specific pattern (alternating between two specific values, descending, ascending, etc.) while others may be stable. Tell me the min/max/average and the pattern it follows, if any. Also, make sure that your screen settings are such that it won't blank after only a couple seconds. If you need help, just let me know.

It could be that the bouncing is due to voltage inaccuracy with multiple batteries. Can you test your device using a single battery instead of dual batteries? Some devices don't support this, so let me know if that's the case. If you have a multimeter, it may be helpful to do a load test and voltage test as well. Make sure you know what you're doing if you elect to do so.

Also, does issue #9 affect you or do you get weak battery alerts when bouncing occurs?

Lastly, please answer the questions from my previous response.

I don't own an RX200S so I can't run these tests myself. Sorry if it's a bit overwhelming.

**Comment by Daemones795** [comment] 2017-04-19 17:21
So far not affected by #9 but yes im stuck at 80-90% charge max, have tried stock firmware with no problem and am able to get max charge, optimized version bricks my mod so i stuck with generic

**Comment by Daemones795** [comment] 2017-04-19 17:26
And yes i believe it is just the displayed value because as soon as it kicks to the next screen it goes back to normal, i just noticed it happens on watts and amps

**Comment by Daemones795** [comment] 2017-04-19 17:28
All three batteries are at 4.19volts currently

**Comment by arafey** [comment] 2017-04-19 17:39
Ok, at least the device is firing normally. I do want to fix the screen displaying incorrect values, but it's not a high priority. 

Since I don't own a multi-battery device, it will have to wait until some more progress is made on #21 because this problem requires some more reverse engineering than what's already been done. I can only do that by decompiling firmware, physically opening up a device, and relying on others' help. 

If the issue is very problematic for you, I recommend trying Arctic Fox or stock firmware in the meantime. I will update this issue when/if there is progress.

**Closed** 2017-04-19 17:45 UTC
Labels: bug, help wanted, low priority, wontfix
