### ISSUE TITLE
Issue with latest build

### ISSUE THREAD

**Issue by Hansson0728** [arafey/openevic#22] opened 2017-04-19 05:07 UTC
Crash on latest build,
I usally have the realtime resistance on the third info row, after upgrade it was showing amps, when i tried to change it to real time resitnce it goes blank (the third field) then the mod hangs until i remove the btteries, also in TC i cant set the temp under 150 C, before it went down to 100 ( not a biggie though i can just even it out with the coil resitance)

**Comment by arafey** [comment] 2017-04-19 05:25
What is the most recent build that doesn't have this problem? If all of them do, try myevic (if you haven't already) and let me know.

**Comment by Hansson0728** [comment] 2017-04-19 05:26
I used the build from before yesterday before it was working fine

**Comment by Hansson0728** [comment] 2017-04-19 05:27
Ive been using myvic for some months but switched to your build last week since its getting updates, super happy so far

**Comment by arafey** [comment] 2017-04-19 05:32
By before yesterday you mean 0.12? And by current build do you mean 0.15? Just trying to localize where exactly the regression occurred so that it's easier to find.

**Comment by Hansson0728** [comment] 2017-04-19 05:32
Yes exactly, sorry i just updated the last comment

**Comment by arafey** [comment] 2017-04-19 05:51
No problem, just trying to be precise.

It's odd that you can't go below 150°. I don't remember changing TC temp range for any devices. 

It's possible that something I merged from another repository has done so. I can revert it easily if that's the case.

I also haven't messed with real-time resistance readings. I have a couple ideas as to what could be causing this. If I made a test build, would you be willing to test it here?

**Comment by Hansson0728** [comment] 2017-04-19 05:52
I can do that

**Comment by arafey** [comment] 2017-04-19 06:14
Let me know if [this build](https://github.com/arafey/openevic/files/931986/openevic-v0-15-oldflags.bin.zip) changes anything.

**Comment by Hansson0728** [comment] 2017-04-19 06:19
Yes this one is not crashing when i switch to the live resistance view on line 3, still womt go below 150 though, ill run with this build for now. Ill get back if i notice something else

**Comment by arafey** [comment] 2017-04-19 06:29
That's about what I expected. This build is exactly the same as 0.15 except that it is compiled differently. You lose a few of the optimizations that are mentioned on the release page, but you get the features and bugfixes. I'll add this build to the releases page for 0.15 and include notes about this problem for other RX2/3 users.

Thank you for testing this.

**Comment by Hansson0728** [comment] 2017-04-19 06:36
No worries, keep it up :)

**Comment by arafey** [comment] 2017-04-19 06:44
Thanks! I'm going to close this issue because we solved the crash. 

I'll investigate the minimum temperature problem. If someone else increased the min TC temp, there's probably a good reason (maybe inaccuracy at such a low temperature). If not, I'll fix it for the next release. 

In the meantime, another workaround you can try is to use a lower wattage in TC mode. You can also adjust the PID values (use a much lower I value and lower P moderately) so that it can't reach 150°, if necessary.

**Closed by arafey** 2017-04-19 06:44 UTC
Labels: bug, regression
